import { Member } from './schema';
export const members: Member[] = [
  {
    id: "MEM-001",
    fullName: "Adebayo Adekunle",
    brandName: "Kunle Farms",
    phone: "+2348012345678",
    email: "admin@afrimart.com",
    status: "Active",
    role: "Admin",
    registrationDate: new Date("2023-05-15"),
    addedBy: "Admin",
    activityLog: [
      { date: new Date("2023-05-15"), action: "Registration", description: "Member registered via admin panel." },
      { date: new Date("2023-05-16"), action: "Approval", description: "Membership approved by Admin." },
    ],
  },
  {
    id: "MEM-002",
    fullName: "Ngozi Okoro",
    brandName: "Ngozi's Spices",
    phone: "+2348023456789",
    email: "ngozi.o@spices.ng",
    status: "Pending",
    role: "Member",
    registrationDate: new Date("2024-01-20"),
    addedBy: "Public Form",
    activityLog: [
      { date: new Date("2024-01-20"), action: "Registration", description: "Member registered via public form." },
    ],
  },
  {
    id: "MEM-003",
    fullName: "Kwame Mensah",
    brandName: "Ghana Gold Cocoa",
    phone: "+233241234567",
    email: "kwame.m@ghanagold.gh",
    status: "Active",
    role: "Admin",
    registrationDate: new Date("2022-11-10"),
    addedBy: "Admin",
    activityLog: [
      { date: new Date("2022-11-10"), action: "Registration", description: "Member registered via admin panel." },
      { date: new Date("2022-11-11"), action: "Approval", description: "Membership approved by Admin." },
    ],
  },
  {
    id: "MEM-004",
    fullName: "Fatima Diallo",
    brandName: "Senegal Shea",
    phone: "+221771234567",
    email: "fatima.d@shea.sn",
    status: "Suspended",
    role: "Member",
    registrationDate: new Date("2023-08-01"),
    addedBy: "User-012",
    activityLog: [
      { date: new Date("2023-08-01"), action: "Registration", description: "Member registered." },
      { date: new Date("2023-08-02"), action: "Approval", description: "Membership approved." },
      { date: new Date("2024-02-05"), action: "Suspension", description: "Account suspended due to policy violation." },
    ],
  },
  {
    id: "MEM-005",
    fullName: "John Mwangi",
    brandName: "Kenya Coffee Exporters",
    phone: "+254722123456",
    email: "john.m@kenyacoffee.co.ke",
    status: "Active",
    role: "Member",
    registrationDate: new Date("2023-02-28"),
    addedBy: "Admin",
    activityLog: [
      { date: new Date("2023-02-28"), action: "Registration", description: "Member registered via admin panel." },
      { date: new Date("2023-03-01"), action: "Approval", description: "Membership approved by Admin." },
    ],
  },
  {
    id: "MEM-006",
    fullName: "Aisha Ibrahim",
    brandName: "Hibiscus Flowers Ltd",
    phone: "+2348034567890",
    email: "aisha.i@hibiscus.com",
    status: "Pending",
    role: "Member",
    registrationDate: new Date("2024-03-12"),
    addedBy: "Public Form",
    activityLog: [
      { date: new Date("2024-03-12"), action: "Registration", description: "Member registered via public form." },
    ],
  },
  {
    id: "MEM-007",
    fullName: "David Ochieng",
    brandName: "Ochieng Cashews",
    phone: "+254712345678",
    email: "david.o@cashews.co.ke",
    status: "Active",
    role: "Member",
    registrationDate: new Date("2023-09-22"),
    addedBy: "User-005",
    activityLog: [
      { date: new Date("2023-09-22"), action: "Registration", description: "Member registered." },
      { date: new Date("2023-09-23"), action: "Approval", description: "Membership approved." },
    ],
  },
  {
    id: "MEM-008",
    fullName: "Chidinma Eze",
    brandName: "Eze Ginger Exports",
    phone: "+2348045678901",
    email: "chidinma.e@ezeginger.com",
    status: "Active",
    role: "Member",
    registrationDate: new Date("2022-07-18"),
    addedBy: "Admin",
    activityLog: [
      { date: new Date("2022-07-18"), action: "Registration", description: "Member registered via admin panel." },
      { date: new Date("2022-07-19"), action: "Approval", description: "Membership approved by Admin." },
    ],
  },
  {
    id: "MEM-009",
    fullName: "Chuks Okezie",
    brandName: "Okezie Agro",
    phone: "+2348056789012",
    email: "chuksokezie@gmail.com",
    status: "Active",
    role: "Admin",
    registrationDate: new Date("2024-04-01"),
    addedBy: "Admin",
    activityLog: [
      { date: new Date("2024-04-01"), action: "Registration", description: "Member registered via admin panel." },
      { date: new Date("2024-04-01"), action: "Approval", description: "Membership approved by Admin." },
    ],
  },
];